name: manage-azure-policy-5f1d5f1b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy-definition/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**'
#      - 'policy-definition/policies/Kubernetes_cluster_containers_should_only_use_allowed_capabilities_c26596ff-4d70-4e6a-9a30-c2506bd2f80c/**'
#      - .github/workflows/manage-azure-policy-5f1d5f1b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_5f1d5f1b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy-definition/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**
          policy-definition/policies/Kubernetes_cluster_containers_should_only_use_allowed_capabilities_c26596ff-4d70-4e6a-9a30-c2506bd2f80c/**
